### ISSUE TITLE
No longer seems to work with EasyApache

### ISSUE THREAD

**Issue by gigatux** [DamianZaremba/easyapache-modules#1]
When using this with current EasyApache builds (at least as of September 2013) the build fails with:

```
-- Begin step 'Loading mod_rpaf into Apache' --
!! Invalid arguments !!
```

So it looks like the arguments for $self->ensure_loadmodule_in_httpdconf might have changed.

**Comment by BarryCarlyon** [comment]
I have this too :-(

**Comment by DamianZaremba** [comment]
I'll try and take a look at this issue tonight, need to install a cPanel box to test it on. Been on my todo list for a while, but I don't regularly admin cPanel anymore.

**Comment by DamianZaremba** [comment]
If you want to try something in dev/stage to see if it works, you might get it working by replacing

``` perl
return $self->ensure_loadmodule_in_httpdconf('rpaf', 'mod_rpaf-2.0.so');
```

with

``` perl
$self->include_directive_handler(
    { 
        'addmodule' => 'mod_rpaf',
        'loadmodule' => 'mod_rpaf-2.0.so'
    } 
);
```

It might fail, because I can't tell right now if it requires including a config file and won't uninstall properly as it needs directives to strip the settings back out of the config file.

Do note that this package includes 0.6, there is now 0.8 out - I am not responsible for any security issues you cause that have been fixed in .7 or .8 ;) I'll update the packages also, later.

**Comment by BarryCarlyon** [comment]
```
-- Begin step 'Loading mod_rpaf into Apache' --
Use of uninitialized value in concatenation (.) or string at /var/cpanel/perl/easy/Cpanel/Easy/Utils/HttpdConf.pm line 1053.
!! Invalid arguments !!
```

I tried:

```
return $self->include_directive_handler(
    { 
        'include_path' => '',
        'addmodule' => 'mod_rpaf',
        'loadmodule' => 'mod_rpaf-2.0.so'
    } 
);
```

But that didn't derp on line 1053 just a back to bad args.

Drawing inspiration from
Line 302 of /var/cpanel/perl/easy/Cpanel/Easy/UtilsPHP.pm

```
    return $self->include_directive_handler(
        {
            'include_path' => '/usr/local/apache/conf/php.conf',
            'addmodule'    => 'mod_bwlimited',
            'loadmodule'   => 'bwlimited_module',
        }
    );
 }
```

Tried a handful of things but no joy. Back to other things for now :-D

**Comment by DamianZaremba** [comment]
This should now be fixed on master

``` bash
root@cpanel-test [~]# git clone git@github.com:DamianZaremba/easyapache-modules.git
root@cpanel-test [~]# cd easyapache-modules/
root@cpanel-test [~/easyapache-modules]# make install
mkdir -p /var/cpanel/easy/apache/custom_opt_mods/Cpanel/Easy/
cp -f *.pm /var/cpanel/easy/apache/custom_opt_mods/Cpanel/Easy/
cp -f *.tar.gz /var/cpanel/easy/apache/custom_opt_mods/Cpanel/Easy/
root@cpanel-test [~/easyapache-modules]# /scripts/easyapache # Enable cloudflare/rpaf/wsgi
root@cpanel-test [~/easyapache-modules]# grep -i mod_cloudflare /etc/httpd/conf/httpd.conf
LoadModule cloudflare_module modules/mod_cloudflare.so
root@cpanel-test [~/easyapache-modules]# grep -i mod_rpaf /etc/httpd/conf/httpd.conf
LoadModule rpaf_module modules/mod_rpaf.so
root@cpanel-test [~/easyapache-modules]# grep -i mod_wsgi /etc/httpd/conf/httpd.conf
LoadModule wsgi_module /usr/local/apache/modules/mod_wsgi.so
```

**Comment by DamianZaremba** [comment]
I've tagged 1.0 before these changes, which should cover EA 2.x usage.

**Comment by BarryCarlyon** [comment]
!! Build Complete! !!

All good for me off master :-D

**Comment by BarryCarlyon** [comment]
All good and working fine (after adding the relevant apache conf)

Cookies all round!
